matrix:
  include:
    - language: c
      sudo: false
      install:
        - source <(cat install-travis-ci-arduino.sh)
      script:
        - build_main_platforms
        
notifications:
  email:
    on_success: change
    on_failure: change
